export const GET_OFFERS_REQUESTED = "GET_OFFERS_REQUESTED";
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";
export const GET_OFFERS_FAILED = "GET_OFFERS_FAILED";

export const FAVORITE_REQUESTED = "FAVORITE_REQUESTED";
export const ADD_FAVORITE_OFFER = "ADD_FAVORITE_OFFER";
export const REMOVE_FAVORITE_OFFER = "REMOVE_FAVORITE_OFFER";

export const FILTER_REQUESTED = "FILTER_REQUESTED";
export const ADD_NEW_FILTER = "ADD_NEW_FILTER";
